[features]
seeds = false
skip-lint = false
[programs.localnet]
l3 = "4vDhf9BpYKzHqvwK1dW162fTuPzCUj9ZSz65hsM8zuFU"
# test
[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
